# Generated by Django 5.1.4 on 2025-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', 'Drama'), ('2', 'Crime'), ('3', 'Sci-Fi'), ('4', 'Action'), ('5', 'Horror'), ('6', 'Fantasy'), ('7', 'Thriller')], max_length=255, null=True),
        ),
    ]
